import AnimatedDiv from '../components/Animate/AnimatedDiv'
import AnimatedContainer from '../components/Animate/AnimatedContainer'
import Image from 'next/image'

const Skyhook = () => {
  return (
    <main id="gyms" className="max-w-sm md:max-w-xl p-10 flex flex-col items-center">
      <AnimatedContainer className="flex flex-col w-full saturate-100 drop-shadow-2xl">
        <AnimatedDiv className="header1">Skyhook</AnimatedDiv>
        <AnimatedDiv className="para pb-5 text-sm italic">Last updated 1/2/24</AnimatedDiv> 
        <AnimatedDiv className="header2 text-amber-500">Get to know the new neighbors</AnimatedDiv>
        <AnimatedDiv className="para">There has been a persistent buzz in my climbing community about the new bouldering gym opening in Southeast Portland. Today I opened Instagram to an ad about <a href='https://www.skyhookbouldering.com/' className='sky-link'>Skyhook</a>, specifically that they were offering hard hat tours. A phone call and a hop across the river later and I was poking around a historical-looking building in the southwest corner of Ladd's Addition. I soon found myself face to face with <a href='https://www.skyhookfitness.com/copy-of-about-1?pgid=lk5zudrk-acd96d9f-2d20-44a9-b73f-2bfed8bc4d2f' className='sky-link'>Cody</a>, Owner, Founder, Head of Construction at Skyhook.</AnimatedDiv>
        <AnimatedDiv className="para">Within minutes of meeting each other, we are talking about the many things Bouldering Project does well. We eventually touch on highly touted ex-SBP and Skyhook setter, ex-pro climber and current international head setter <a href='https://www.instagram.com/r.kenna/' className='sky-link'>Riley Kenna</a>, who has been advising on Euro hold selection like those at the Bouldering Projects. This is a joy to hear because, despite being up to twice as expensive and requiring significant lead time to acquire, Euro holds feel <i>awesome</i> to climb on. Honestly I'm not really sure why. But Adam Ondra seems to like them too. </AnimatedDiv>
        <AnimatedDiv className="mt-7 w-full flex flex-col items-center">
          <span className="mb-2 text-xs italic">Adam really likes climbing, and he also loves Euro holds. Me too, Adam. Me too.</span>
          <a href='https://euroholds.com/en/adamondra?module=adamondra' className='w-4/5 flex justify-center'><img src='https://patslookout.s3.us-west-2.amazonaws.com/skyhook/ondra.png' className='shadow rounded block'/></a>
        </AnimatedDiv>
        <AnimatedDiv className="para">We turn our attention to the space in front of us. The floor space is about the same as SW Circuit, but with the higher walls the wall footage is actually about the same as NE Circuit. Cody explains to me the evolution of modern gym guidelines on generously expanding padding and spacing between features, ideas he is keen on adopting. </AnimatedDiv>
        <AnimatedDiv className="para">About a third of the walls have already taken form. They are impressive. The features are big and bold, like the proud floor to ceiling arete, or the 70 degree overhang that yawns out and over into a large arch, a feature reminiscent of ABP's arch. There's something about the proportions, or perhaps how they are situated near each other, that draws you in as a climber. Perhaps it's the way the size and shape will support extended move sequences, or how their proximity to each other will force unique and playful transitions from one to another. Cody also mentions the in-house volume factory, which will supply bespoke volumes for the ability to fine tune the walls at will. Cody mentions that 400 volumes will be available opening day.</AnimatedDiv>
        <AnimatedDiv className="para">Looking up, the roof above us is made of exposed beams, and is about a body length above the highest point of the walls- too low to allow topouts, which I was never a fan of anyways. </AnimatedDiv>
        <AnimatedDiv className="para">Cody also emphasizes his attraction to slab and points out a wide slab wall in the back. I have always loved a good outdoor slab, but in my experience, indoor slab is quite hit or miss, and seems to depend on how much frictioned surface area is available for use. For example, in Portland I've only enjoyed gym slab at PRG Beaverton because its new holds are so sticky that you can focus more on technique and less on the fact that your polished foothold will blow at any second. Thankfully, the Skyhook walls will have Bouldering Project-style rough texturing, which will support thin smearing literally anywhere on the wall. Great choice.</AnimatedDiv>
        <AnimatedDiv className="para">He points at a back wall which will be a large live plant wall. The houseplant rancher in me cheers. We talk about how lounge spaces will be scattered throughout, and how wide walkways are intended to obviate squirm-dodging. </AnimatedDiv>
        <AnimatedDiv className="para">Through a garage door-sized opening is a smaller area which will house a few more walls, an approximately 50' x 25' workout area and a living-room sized coworking space and more lounge areas. Cody states the coworking room doubles as a small birthday party space but is quick to emphasize larger parties will be directed to Tigard. This room, like the main climbing chamber, has large South-facing windows (currently boarded up) that will probably provide plenty of natural lighting. A spray wall will be here, and one day, a systems board, which will not be present at opening (Cody mentions it will be a priority once membership revenue starts rolling in). I daydream about what I've always wanted out of Portland gyms- somewhere bright and cheerful to program and work my brain straight into overheating, and then another somewhere 10 feet away to ventilate out through my finger tendons. </AnimatedDiv>
        <AnimatedDiv className="para">The last area appears to be the front entryway. A strangely beak-shaped foyer with a low ceiling. We talk about 24/7 access, about the extra hurdles of insurance, and planned safety measures like Life Alert tags, double entry monitoring, double gates. </AnimatedDiv>
        <AnimatedDiv className="para pb-5">It is clear to me he and his team have put a lot of thought into the design of the gym. I invite him to share about his background. Cody was raised in Clackamas and started climbing decades ago when his cousin was working as a Ranger in the mecca known as Yosemite. For a blissful couple weeks, they wandered around hiking and climbing rocks. I relate how I had a similar experience, and how we have probably both been chasing that high ever since... </AnimatedDiv>
        <AnimatedDiv className="header2 text-amber-500">Bottom line?</AnimatedDiv>
        <AnimatedDiv className="para">I think my impression is that Cody and his team have a specific vision of a climbing gym that does two things: feel hip, bright, and welcoming, and also have state of the art climbing and setting. I have high hopes they can achieve both of these things. I wonder if the black walls won't feel as bright and playful as the Bouldering Project seafoam green, but this may be offset by the ample natural lighting, planned two tiered artificial lighting system, and cheerful decor (like the live wall). Cody comments that the dark walls are his way of supporting the setters with a canvas, as opposed to fighting their creations, but that he is also open to changing it up if it turns out it just isn't the vibe. </AnimatedDiv>
        <AnimatedDiv className="para">I am also concerned that the pure wall footage isn't enough to gracefully handle popularity despite very conscious efforts to amply space features apart. I concede that even SBP frequently struggles with this, but their roofs are higher which might help some psychologically. Frankly, this will be a good problem for Skyhook to have, but not for those brave souls who insist on climbing during the gym rush hours of 5-7pm ;) </AnimatedDiv>
        <AnimatedDiv className="para">A worst case scenario is that the large North and South facing windows and lighting system are somehow still not quite good enough to brighten up the dark walls, and we get yet another dark, crowded gym, but with excellent Euro Holds and routesetting. But the more optimistic (and probable) scenario is that Skyhook becomes a small Portland Bouldering Project: bright, spacious, welcoming and cheerful, a place where friends can come and feel good climbing on great routesetting and then go next door to Double Dragon to grab a bite and cement a good time. Did I mention 24/7 access?</AnimatedDiv>
        <AnimatedDiv className="para">I think this gym is a great deal, especially with the promo being offered right now, particularly for those that will make good use of the off-hour access (like my friends with young children and/or in healthcare), those that like to mix coworking and climbing like me, and those that enjoy nice climbing holds and big, fun Bouldering Project-style features and setting. I am stoked to return in March. ✌️</AnimatedDiv>
      </AnimatedContainer>
    </main>
  )
}

export default Skyhook;