import AnimatedDiv from '../components/Animate/AnimatedDiv'
import AnimatedContainer from '../components/Animate/AnimatedContainer'
import Image from 'next/image'

const Skyhook = () => {
  return (
    <main id="gyms" className="max-w-sm md:max-w-xl p-10 flex flex-col items-center">
      <AnimatedContainer className="flex flex-col w-full saturate-100 drop-shadow-2xl">
        <AnimatedDiv className="header1">Skyhook</AnimatedDiv>
        <AnimatedDiv className="para pb-5 text-sm italic">Last updated 1/2/24</AnimatedDiv> 
        <AnimatedDiv className="header2 text-amber-500">Get to Know the New Neighbors</AnimatedDiv>
        <AnimatedDiv className="para">There has been a persistent buzz in my climbing community about the new bouldering gym opening in Southeast Portland. Today I opened Instagram to an ad about <a href='https://www.skyhookbouldering.com/' className='sky-link'>Skyhook</a>, specifically that they were offering hard hat tours. A phone call and hop across the river later, and I'm driving into the hip part of town, specifically the southwest corner of Ladd's Addition, next to Double Dragon. Great location, I think to myself. I pull up to a historical-looking building, and I soon find myself face to face with <a href='https://www.skyhookfitness.com/copy-of-about-1?pgid=lk5zudrk-acd96d9f-2d20-44a9-b73f-2bfed8bc4d2f' className='sky-link'>Cody</a>, Owner, Founder, Head of Construction at Skyhook.</AnimatedDiv>
        <AnimatedDiv className="para">Within minutes of meeting each other, we are talking about the many things Bouldering Project does well. We eventually touch on highly touted ex-SBP and Skyhook setter, ex-pro climber and current international head setter <a href='https://www.instagram.com/r.kenna/' className='sky-link'>Riley Kenna</a>, who has been advising on Euro hold selection like those at the Bouldering Projects. This is a joy to hear because, despite being up to twice as expensive and requiring significant lead time to acquire, Euro holds feel <i>awesome</i> to climb on. Honestly I'm not really sure why. But Adam Ondra seems to like them too. </AnimatedDiv>
        <AnimatedDiv className="mt-7 w-full flex flex-col items-center">
          <a href='https://euroholds.com/en/adamondra?module=adamondra' className='flex w-4/5 justify-center'><img src='https://patslookout.s3.us-west-2.amazonaws.com/skyhook/ondra.png' className='shadow rounded block'/></a>
          <span className="m-1 w-4/5 text-xs italic">Adam really likes climbing, and he also loves Euro holds. Me too, Adam. Me too.</span>
        </AnimatedDiv>
        <AnimatedDiv className="para">About a third of the walls have already taken form, painted Skyhook black. They are impressive. The features are big and bold, like the proud floor to ceiling arete, or the 70 degree overhang that yawns out and over into a large arch, a feature reminiscent of ABP Springdale's arch. There's something about the proportions, or perhaps how they are situated near each other, that draws you in as a climber. Perhaps it's the way the size and shape will support extended move sequences, or how their proximity to each other will force unique and playful transitions from one to another. Cody also mentions the in-house volume factory, which will supply bespoke volumes for the ability to fine tune the walls at will. Cody mentions that 400 volumes will be available opening day.</AnimatedDiv>
        <AnimatedDiv className="para">We turn our attention to the spacing of the gym as Cody waves his arms to sketch floor padding and walkways into life. While the floor space is about the same as SW Circuit, the higher walls of Skyhook boost the wall footage to that of NE Circuit. Cody expounds on modern gym guidelines, which have generously expanded the padding between features. We talk about how lounge spaces will be scattered throughout, and how wide walkways are intended to obviate squirm-dodging. Looking up from the floor towards the roof, I see that the ceiling's exposed beams are about a body length above the highest point of the walls- too low to allow topouts, which I was never a fan of anyways. Overall, with Cody's help I can certainly get a sense of how the space will breathe, although no one can say for sure until Skyhook starts drawing crowds. Speaking of breathing spaces, I'm personally looking forward to the large plant wall planned near the windows. The houseplant rancher in me cheers.</AnimatedDiv>
        <AnimatedDiv className="para">Cody points to a wide slab in a sunny corner behind the arch and matter-of-factly states that he likes slab. I also love a good slab. However, in my experience, indoor slab is quite hit or miss, and seems to depend on how much frictioned surface area is available for use. For example, in Portland I've only enjoyed gym slab at PRG Beaverton because its new holds are so sticky that you can focus more on technique and less on the fact that your polished foothold will blow at any second. Thankfully, the Skyhook walls will have Bouldering Project-style rough texturing, which will support thin smearing literally anywhere on the wall. Great choice.</AnimatedDiv>
        <AnimatedDiv className="para">Through a garage door-sized opening is a smaller area which will house a few more walls, an approximately 50' x 25' workout area and a living-room sized coworking space and more lounge areas. Cody states the coworking room doubles as a small birthday party space but is quick to emphasize larger parties will be directed to Tigard. This room, like the main climbing chamber, has large South-facing windows (currently boarded up) that will probably provide plenty of natural lighting. A spray wall will be here, and one day, a systems board, which will not be present at opening (Cody mentions it will be a priority once membership revenue starts rolling in). I daydream about what I've always wanted out of Portland gyms- somewhere bright and cheerful to program and work my brain straight into overheating, and then another somewhere 10 feet away to ventilate out through my finger tendons. </AnimatedDiv>
        <AnimatedDiv className="para">The last area appears to be the front entryway. A strangely beak-shaped foyer with a low ceiling. <b>Skyhook will have 24/7 access.</b> We brush over what this entails: about the extra hurdles of insurance, safety measures like Life Alert tags, double entry monitoring, double gates.</AnimatedDiv>
        <AnimatedDiv className="para pb-5">Suddenly, I'm curious about Cody's climbing influences, and I invite him to share about his background. Cody was raised in Clackamas and started climbing decades ago when his cousin was working as a Ranger in that holy mecca known as Yosemite. For a blissful couple weeks, they wandered around hiking and climbing rocks. I relate how I had a similar experience, and how we have probably both been chasing that high ever since... </AnimatedDiv>
        <AnimatedDiv className="header2 text-amber-500">Bottom line?</AnimatedDiv>
        <AnimatedDiv className="para">I am frankly concerned that the pure wall footage isn't enough to gracefully handle popularity despite very conscious efforts to amply space features apart. I concede that even SBP frequently struggles with this, but their roofs are higher which might help some psychologically. This will be a good problem for Skyhook to have, but not for those brave souls who insist on climbing during the gym rush hours of 5-7pm. I'd say a worst case scenario is that the large north and south-facing windows and lighting system are somehow still not quite bright enough to liven up the black climbing walls, and we get yet another dark, crowded gym, albeit with excellent Euro Holds and routesetting. </AnimatedDiv>
        <AnimatedDiv className="para"><i>However</i>, the more optimistic and, in my estimation, probable scenario is that Skyhook becomes a small Portland Bouldering Project: a bright, spacious, and cheerful spot for climbers to get those all-important endorphins going. It is clear to me this will be a modern-style bouldering gym with plenty of perks. I am most excited for 24-hour access (!!), the lounge spaces, and the Bouldering Project-style features and setting, and I will be stoked to return in March for Opening Day! ✌️</AnimatedDiv>
      </AnimatedContainer>
    </main>
  )
}

export default Skyhook;